### ISSUE TITLE
`aria-describedby`: root.getElementById is not a function

### ISSUE THREAD

**Issue by e2000mann** [guidepup/virtual-screen-reader#48]
# Issue

Setup:

- Node version: v20.0.0
- Virtual Screen Reader version: v0.17.0
- Environment:  vitest v1.1.3

### Code
```ts
describe('Screen Reader Tests', () => {
  it('should traverse the widget announcing the expected roles and content', async () => {
    const html = `<button aria-describedby="trash-desc">Move to trash</button>
    …
    <p id="trash-desc">
      Items in the trash will be permanently removed after 30 days.
    </p>`;
    const body = document.createElement('body');
    body.innerHTML = html;

    // Start your Virtual Screen Reader instance
    await virtual.start({container: body});

    // Navigate your environment with the Virtual Screen Reader similar to how your users would
    while ((await virtual.lastSpokenPhrase()) !== 'end of document') {
      await virtual.next();
    }

    const text = await virtual.spokenPhraseLog();

    // Assert on the kind of things your users would see and hear when using screen readers
    expect(text).toEqual(['document', 'button, Move to trash, trash-desc', '…', 'Items in the trash will be permanently removed after 30 days.', 'end of document']);

    // Stop your Virtual Screen Reader instance
    await virtual.stop();
  });
});
```

### Expected Result
For test to pass

### Actual Result
```bash
TypeError: root.getElementById is not a function
 ❯ map ../../node_modules/dom-accessibility-api/sources/util.ts:101:22
 ❯ queryIdRefs ../../node_modules/dom-accessibility-api/sources/util.ts:101:5
 ❯ computeAccessibleDescription ../../node_modules/dom-accessibility-api/sources/accessible-description.ts:16:31
 ❯ getAccessibleDescription ../../node_modules/@guidepup/virtual-screen-reader/lib/getNodeAccessibilityData/getAccessibleDescription.js:7:104
 ❯ getNodeAccessibilityData ../../node_modules/@guidepup/virtual-screen-reader/lib/getNodeAccessibilityData/index.js:39:91
 ❯ ../../node_modules/@guidepup/virtual-screen-reader/lib/createAccessibilityTree.js:147:234
 ❯ growTree ../../node_modules/@guidepup/virtual-screen-reader/lib/createAccessibilityTree.js:134:21
 ❯ createAccessibilityTree ../../node_modules/@guidepup/virtual-screen-reader/lib/createAccessibilityTree.js:230:18
```

### Thoughts
From what I can tell, it looks like it is trying to find the id within the button element rather than the global DOM. This is valid HTML taken directly from https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby

**Comment by jlp-craigmorten** [comment]
Hi @e2000mann 👋 

This issue here appears to be an upstream dependency [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api/) not handling the created `body` element gracefully.

In your snippet you are creating a `body` Node in isolation to the `document` meaning the root node is the `body` itself and not the `document`. `dom-accessibility-api` doesn't cater to this and subsequently throws an error trying to call `.getElementById()` on the `body` Node itself, which doesn't exist (the method _only_ exists on the `document`).

There are a few things can do to resolve:

1. Assign the HTML to the `body` that already exists on the `document`
2. Append the new `body` element to the `document` if one does not already exist
3. Raise an issue on the [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api/) asking for `computeAccessibleDescription()` and other methods to handle a detached `body` element (and maybe other detached element scenarios).

For (1), you can do:

```ts
describe('Screen Reader Tests', () => {
  it('should traverse the widget announcing the expected roles and content', async () => {
    const html = `<button aria-describedby="trash-desc">Move to trash</button>
    …
    <p id="trash-desc">
      Items in the trash will be permanently removed after 30 days.
    </p>`;
    document.body.innerHTML = html;

    // Start your Virtual Screen Reader instance
    await virtual.start({container: body});

    // ... rest of test code
  });
});
```

**Comment by e2000mann** [comment]
Hi, option 1 seems to work ok, thanks

**Comment by jlp-craigmorten** [comment]
> Hi, option 1 seems to work ok, thanks

Awesome stuff!

I've raised an issue against https://github.com/eps1lon/dom-accessibility-api/issues/1026 in the meantime to suggest a fix, I don't see why we shouldn't be able to support detached nodes in scenarios such as this.

**Comment by jlp-craigmorten** [comment]
Closing this for now as nothing can do until the upstream package is fixed.
